### ISSUE TITLE
Why will upickle convert `Option[T]` to array `[...]`?

### ISSUE THREAD

**Issue by freewind** [com-lihaoyi/upickle#75] opened 2015-03-09 13:39 UTC
I found if there is an option value in case class, it will be converted to `[]` in js

```
case class User(name:String, age: Option[Int])

val user1 = User("Free", Some(100))
val user2 = User("Wind", None)
```

Will be converted to:

```
{ "name": "Free", "age": [100] }
{ "name": "Wind", "age": [] }
```

Why use array here rather than:

```
{ "name": "Free", "age": 100 }
{ "name": "Wind" }
```

The later is the one I usually do with other scala json libraries

**Comment by tindzk** [comment] 2015-03-09 13:48
This sounds reasonable, but how would you encode ``Some(None): Option[Option[Int]]``?

**Comment by freewind** [comment] 2015-03-09 17:02
Never thought of that. You are right, it's reasonable to use array for Option. 

But for the json readers, the array type may confuse them because they may think that value can have multiple items. Is there any way to customize the format?

**Comment by tindzk** [comment] 2015-03-09 17:21
No, unfortunately, it is not possible to customise the format. I agree that uPickle should provide an option to change the default behaviour. You could have a look at https://github.com/tindzk/upickle/commits/change-sumencoding or https://github.com/lihaoyi/upickle/pull/65 on how to introduce a configuration object. However, I'd prefer a solution with the Cake pattern, see https://github.com/lihaoyi/upickle/issues/59#issuecomment-72096982.

**Comment by lihaoyi** [comment] 2015-03-09 22:49
Closing this for now, feel free to talk on the other issues

**Comment by netvl** [comment] 2015-03-24 13:58
@tindzk,
> but how would you encode `Some(None): Option[Option[Int]]`?

There is a simple answer on that. `Some(None): Option[Option[Int]]` should be encoded as `[[]]` when it is a standalone value or a part of a collection, but if it is a part of case class:
```scala
case class Weird(value: Option[Option[Int]])
```
then the "outer" option should be encoded as a presence or absence of the value, while the inner option should be encoded as an array:
```scala
write(Weird(None))       shouldEqual """{}"""
write(Weird(Some(None))) shouldEqual """{"value":[]}"""
write(Weird(Some(1234))) shouldEqual """{"value":[1234]}"""
```

This does require that the macro-based serializer knowns how to handle optional fields, but it is not impossible and certainly makes sense.

**Comment by tindzk** [comment] 2015-03-24 15:24
This seems like a good approach to me. We should reopen the ticket.

**Comment by GiantToast** [comment] 2015-08-13 18:56
Scala newb here, so this is probably wrong, but wouldn't:
 `write(Weird(Some(1234))) shouldEqual """{"value":[1234]}"""` 
in the case above be:
 `write(Weird(Some(Some(1234)))) shouldEqual """{"value":[1234]}"""`

I'm also running into this issue, so it would be great to get this kind of Option handling in there.

**Comment by lihaoyi** [comment] 2015-08-14 06:05
@tindzk sure I can re-open it. I probably won't put in any work into fixing this, but now that uPickle's configurable via instantiating your own custom bundles it'd be cool if someone created a bundle/trait with this behavior

**Comment by lihaoyi** [comment] 2016-01-24 04:39
Closing out of inactivity

**Closed by lihaoyi** 2016-01-24 04:39 UTC

**Comment by l15k4** [comment] 2016-02-23 14:50
This works writer is applied for `Some(v)` : 
```scala
  implicit val optHavingWriter = upickle.default.Writer[Option[HavingSpec]]{
    case Some(v) => writeJs[HavingSpec](v)
    case None => Js.Null
  }
```

This one too : 
```scala
  implicit val optBooleanWriter = upickle.default.Writer[Option[Boolean]]{
    case Some(v) => writeJs[Boolean](v)
    case None => Js.Null
  }
```

But these are not : 
```scala
  implicit val optStringWriter = upickle.default.Writer[Option[String]]{
    case Some(v) => writeJs[String](v)
    case None => Js.Null
  }
  implicit val optIntWriter = upickle.default.Writer[Option[Int]]{
    case Some(v) => writeJs[Int](v)
    case None => Js.Null
  }
```

Unfortunately generic types doesn't work at all, so I have to list a custom writer for each type : 
```scala
  implicit def optWriter[T : Writer] = upickle.default.Writer[Option[T]]{
    case Some(v) => writeJs[T](v)
    case None => Js.Null
  }
```

It would be cool if it worked even for `String` and `Int` ... any idea ?

**Comment by asdcdow** [comment] 2018-05-10 22:41
You actually can write a generic replacement for the `Option` `Reader` and `Writer`.  This trick is that you need to shadow the one that comes with upickle.  So, you can do it with the following:
```
  implicit def OptionReader[T: Reader]: Reader[Option[T]] = reader[Js.Value].map[Option[T]]{
    case Js.Null => None
    case jsValue => Some(read[T](jsValue))
  }
  implicit def OptionWriter[T: Writer]: Writer[Option[T]] = writer[Js.Value].comap {
    case Some(value) => write(value)
    case None => Js.Null
  }
```
This only works because The `Reader` has the name `OptionReader` and the `Writer` has the name `OptionWriter`.  These are the names of instances provided by upickle.  Since we are providing new ones with the same name, the ones provided by upickle will be shadowed and ignored.

**Comment by mycaule** [comment] 2018-12-10 15:13
One common use case would be to read `{"a": "x", "b": "y"}` to `case class MyCC(a: String, b: String, c: Option[String])` so that it matches `MyCC("x", "y", None)`.

**Comment by sstadick** [comment] 2020-05-15 14:47
Did anyone ever come up with a good way of doing this such that writing a `Some(obj)` is not written as an array AND `None` is not written at all? @asdcdow 's solution, and the solution in the [docs](https://github.com/lihaoyi/upickle/blob/master/upickle/test/src/upickle/example/OptionsAsNullTests.scala#L10-L23) makes `Some` write like the OP wants, but they also make `None` 's write as nulls.  

I've tried playing with the `OptionWriter` source, but I'm just not understanding it's visitor pattern / array writing. It also seems like `NoneWriter` and `SomeWriter` do nothing? 

I'm also `serializeDefaults = true`, which removes that route. 

For others who can't figure this out, at least jq can hack around it:

```
jq 'walk( if type == "object" then with_entries(select(.value != null)) else . end)'
```

I guess I could write the json string, rewalk it and remove nulls, then write it again, but there must be a way to do this by overriding `OptionWriter` that I'm not seeing.

**Comment by lihaoyi** [comment] 2024-07-05 02:36
Should be fixed by https://github.com/com-lihaoyi/upickle/pull/598

**Comment by lolgab** [comment] 2024-07-06 12:50
Duplicate of https://github.com/com-lihaoyi/upickle/issues/528
