### ISSUE TITLE
The 18 digit numbers generated by the snowflake algorithm will lose accuracy after reading

### ISSUE THREAD

**Issue by mokexinxin** [com-lihaoyi/upickle#522] opened 2023-09-14 10:01 UTC
Hello:
I want to use JSON to read the 18 digit numbers generated by the snowflake algorithm, but I encountered an accuracy loss issue after reading, as follows
`
{'a':738529527931269425}
`
But after I ran it, I showed the following results:
`
{"a":738529527931269376}
`

The running result shows incorrect numbers, missing is accuracy. If I want to fully obtain this number without converting it to a string, is there a solution?

Note: This issue has been encountered while running sjsonnet. Preliminary troubleshooting may be in this project, and we hope the author can help solve it. 
Thank you very much!

**Comment by lihaoyi** [comment] 2023-09-14 10:45
duplicate of https://github.com/com-lihaoyi/upickle/issues/520#issue-1895759120

**Closed by lihaoyi** 2023-09-14 10:45 UTC
