### ISSUE TITLE
Issue decoding zero-width non-breaking space in JSON string, via ujson.read(InputStream)

### ISSUE THREAD

**Issue by Facsimiler** [com-lihaoyi/upickle#417] opened 2022-12-06 09:11 UTC
I'm developing an application that acts as a git filter, which converts a proprietary file format that contains embedded text files into JSON. Some of the files include a _byte-order mark_ (_BOM_) character that indicates how the file is encoded. (For example, some of the text files might be encoded using UTF-16 LE. Meanwhile, the JSON file is written using a UTF-8 encoding.) The lines in each text file are then stored as a JSON array of strings, together with a field describing the encoding, so that I can convert the JSON back into the proprietary file format, reconstructing the original contents.

I'm using the `ujson.writeToOutputStream` method to write the JSON file, and I've tried this writing the output as-is, and by encoding _Unicode_ characters.

For example, let's say that the proprietary file format contains a single text file, like this:

```
<BOM>Hello, world!
```

Where `<BOM>` represents the _byte-order mark_ character, the _zero-width non-breaking space_ character, with _Unicode_ codepoint 0xFEFF.

If the `encodingUnicode` argument to `writeToOutputStream` is false, then the resulting JSON file looks like this:

```
{
  "entries": [
    {
      "encoding": "utf-16",
      "contents": [
        "<BOM>Hello, world!"
      ]
    } 
  ]
}
```

Note that the BOM is included in the output (but isn't a visible character).

If I set the `encodingUnicode` argument to true, then the resulting JSON file looks like this:

```
{
  "entries": [
    {
      "encoding": "utf-16",
      "contents": [
        "\ufeffHello, world!"
      ]
    } 
  ]
}
```

such that the BOM character is escaped.

However, in both cases, when I read the JSON file back in with the `ujson.read(InputStream)` method, the first string belonging to the contents field is read as `ï»¿Hello, world!`. In other words, `ujson.read` is not processing the BOM character from the JSON string correctly. Instead of creating a single Unicode character with a codepoint of 0xFEFF, it is creating three characters with codepoints 0xEF, 0xBB and 0xBF. These are the same three characters that represent the UFT-8 encoding of the BOM character, which surely isn't a coincidence.

Or am I missing something?

I'm not sure if this effects other multi-byte Unicode characters.

**Comment by lihaoyi** [comment] 2023-03-12 02:31
Seems to be a duplicate of https://github.com/com-lihaoyi/upickle/issues/413

**Closed by lihaoyi** 2023-03-12 02:31 UTC
